module

/-
Copyright (c) 2026 Yuren Tang. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yuren Tang
-/

public import Erdos289
import Erdos289.SignedInverse
import Erdos289.SignedInverseAtom
import Erdos289.SignedInverseReservoir
import Erdos289.SignedInverseConflict
import Erdos289.RowSupply
import Erdos289.BadCarriers
import Erdos289.RowTruncation
import Erdos289.RowCertificate

/-!
# Transitive trust audit

`lake build` succeeding means every declaration has a proof term.  It does not
mean the proof closure is free of assumptions: a theorem can be fully elaborated
and still depend transitively on a `sorry` upstream.  This module is the check
that does mean that.

Each exported theorem's transitive axiom set is pinned with `#guard_msgs`, so a
`sorryAx` or a new project axiom introduced by any future change — including one
arriving through a dependency bump — turns the build red instead of scrolling
past in a log.  The accepted dependencies are the ordinary foundations inherited
from mathlib.

This file is generated by `scripts/gen_audit.py`; edit `scripts/audit_decls.txt`
and regenerate rather than editing it by hand.
-/

/-- info: 'Erdos289.comparablePrimeSupply_explicit' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.comparablePrimeSupply_explicit

/-- info: 'AffineCorrection.FreeClosure.hom_le_of_edge_le' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms AffineCorrection.FreeClosure.hom_le_of_edge_le

/-- info: 'AffineCorrection.CyclicLadder.zmod_generatesIn_pred' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms AffineCorrection.CyclicLadder.zmod_generatesIn_pred

/-- info: 'AffineCorrection.intervalSpectrum_cofinite' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms AffineCorrection.intervalSpectrum_cofinite

/-- info: 'Erdos289.support_grade_additive' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.support_grade_additive

/-- info: 'Erdos289.binaryBlock_blockSize' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.binaryBlock_blockSize

/-- info: 'Erdos289.ternaryBlock_blockSize' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.ternaryBlock_blockSize

/-- info: 'Erdos289.endpoint_inclusion_switch' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.endpoint_inclusion_switch

/-- info: 'Erdos289.remoteLightNeutralGradeOne' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.remoteLightNeutralGradeOne

/-- info: 'Erdos289.rationalPresentation_of_pos' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.rationalPresentation_of_pos

/-- info: 'Erdos289.endpointDeformation_of_unitFractionRefinement' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.endpointDeformation_of_unitFractionRefinement

/-- info: 'Erdos289.positiveExcessBlockification_of_unitFractionRefinement' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.positiveExcessBlockification_of_unitFractionRefinement

/-- info: 'Erdos289.neutralGradePoint' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.neutralGradePoint

/-- info: 'Erdos289.arbitrarilyLightMobility_of_refinement_neutral' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.arbitrarilyLightMobility_of_refinement_neutral

/-- info: 'Erdos289.unitFractionRefinementCofinality' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.unitFractionRefinementCofinality

/-- info: 'Erdos289.arbitrarilyLightMobility' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.arbitrarilyLightMobility

/-- info: 'Erdos289.primePowerStage_le_lower_of_lt' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.primePowerStage_le_lower_of_lt

/-- info: 'Erdos289.primePowerSimpleFiberAddEquiv' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.primePowerSimpleFiberAddEquiv

/-- info: 'Erdos289.reciprocalResidue_mem_annihilatorStage' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.reciprocalResidue_mem_annihilatorStage

/-- info: 'Erdos289.annihilatorStage_mul_eq_sup_of_coprime' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.annihilatorStage_mul_eq_sup_of_coprime

/-- info: 'Erdos289.SignedInverse.complementaryPair' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.SignedInverse.complementaryPair

/-- info: 'Erdos289.SignedInverse.exists_not_dvd_coefficient' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.SignedInverse.exists_not_dvd_coefficient

/-- info: 'Erdos289.SignedInverse.atom_factorsThroughPrimePowerStage' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.SignedInverse.atom_factorsThroughPrimePowerStage

/-- info: 'Erdos289.SignedInverse.atom_filteredTransverse' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.SignedInverse.atom_filteredTransverse

/-- info: 'Erdos289.SignedInverse.ComplementaryPair.exception_multiplier_lt' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.SignedInverse.ComplementaryPair.exception_multiplier_lt

/-- info: 'Erdos289.SignedInverse.carrierFamily_coefficientFiber_card_le_four' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.SignedInverse.carrierFamily_coefficientFiber_card_le_four

/-- info: 'Erdos289.SignedInverse.compatiblePool' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.SignedInverse.compatiblePool

/-- info: 'Erdos289.RestrictedFold.image_card_lower_bound' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.RestrictedFold.image_card_lower_bound

/-- info: 'Erdos289.RestrictedFold.surjective_of_card_bound' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.RestrictedFold.surjective_of_card_bound

/-- info: 'Erdos289.RestrictedFold.coversAtGrade_of_card_bound' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.RestrictedFold.coversAtGrade_of_card_bound

/-- info: 'Erdos289.CyclicLadder.coversAtGrade_zmod' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.CyclicLadder.coversAtGrade_zmod

/-- info: 'Erdos289.Finset.card_le_card_image_mul_of_fiber_bound' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.Finset.card_le_card_image_mul_of_fiber_bound

/-- info: 'Erdos289.QuantitativeTransverseReservoir.rowMin_le_simpleValues_card_mul' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.QuantitativeTransverseReservoir.rowMin_le_simpleValues_card_mul

/-- info: 'Erdos289.aggregateSupport_admissible' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.aggregateSupport_admissible

/-- info: 'Erdos289.aggregateSupport_value' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.aggregateSupport_value

/-- info: 'Erdos289.aggregateSupport_grade' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.aggregateSupport_grade

/-- info: 'Erdos289.IndependentTransversal.hasChunkPacking_of_two_mul_maxDegree_le' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.IndependentTransversal.hasChunkPacking_of_two_mul_maxDegree_le

/-- info: 'Erdos289.IndependentTransversal.hasPacking_one_of_two_mul_maxDegree_le' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.IndependentTransversal.hasPacking_one_of_two_mul_maxDegree_le

/-- info: 'Erdos289.cofiniteSaturation_of_interval_witnesses' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.cofiniteSaturation_of_interval_witnesses

/-- info: 'Erdos289.erdos289_of_positiveRationalSaturation' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.erdos289_of_positiveRationalSaturation

/-- info: 'Erdos289.Support.value_eq_one_of_residue_zero' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.Support.value_eq_one_of_residue_zero

/-- info: 'Erdos289.cofiniteSaturation_one_of_centered' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.cofiniteSaturation_one_of_centered

/-- info: 'Erdos289.GradeAggregation.exists_grades_of_mem_sum_Icc' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.GradeAggregation.exists_grades_of_mem_sum_Icc

/-- info: 'Erdos289.Support.mem_of_between' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.Support.mem_of_between

/-- info: 'Erdos289.Support.blockNat_eq_Icc' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.Support.blockNat_eq_Icc

/-- info: 'Erdos289.erdos289LiteralSeparated_of_statement' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.erdos289LiteralSeparated_of_statement

/-- info: 'Erdos289.erdos289Literal_of_statement' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.erdos289Literal_of_statement

/-- info: 'Erdos289.comparablePrimes_card_isBigO' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.comparablePrimes_card_isBigO

/-- info: 'Erdos289.aggregateSupport_residue' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.aggregateSupport_residue

/-- info: 'Erdos289.cofiniteSaturation_one_of_pools' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.cofiniteSaturation_one_of_pools

/-- info: 'Erdos289.cofiniteSaturation_of_exactSpectrum' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.cofiniteSaturation_of_exactSpectrum

/-- info: 'Erdos289.isAdditiveOn_residue' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.isAdditiveOn_residue

/-- info: 'AffineCorrection.grade_mem_exactSpectrum_of_covers_target' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms AffineCorrection.grade_mem_exactSpectrum_of_covers_target

/-- info: 'Erdos289.binaryBlock_compatibleFor_of_dist' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.binaryBlock_compatibleFor_of_dist

/-- info: 'Erdos289.TransverseReservoir.conflictNeighbors_card_le_of_binary' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.TransverseReservoir.conflictNeighbors_card_le_of_binary

/-- info: 'Erdos289.SignedInverse.reservoir_conflictNeighbors_card_le' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.SignedInverse.reservoir_conflictNeighbors_card_le

/-- info: 'Erdos289.TransverseReservoir.conflictGraph_maxDegree_le_of_binary' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.TransverseReservoir.conflictGraph_maxDegree_le_of_binary

/-- info: 'Erdos289.exists_compatiblePool_of_binary' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.exists_compatiblePool_of_binary

/-- info: 'Erdos289.primePower_squareFiber_card_le_four' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.primePower_squareFiber_card_le_four

/-- info: 'Erdos289.SignedInverse.card_carrierPrimes_ge' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.SignedInverse.card_carrierPrimes_ge

/-- info: 'Erdos289.SignedInverse.exists_multiplier_of_goodOrientations_eq_empty' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.SignedInverse.exists_multiplier_of_goodOrientations_eq_empty

/-- info: 'Erdos289.SignedInverse.card_badCarriers_le' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.SignedInverse.card_badCarriers_le

/-- info: 'Erdos289.SignedInverse.bandCard_isBigO' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.SignedInverse.bandCard_isBigO

/-- info: 'Erdos289.SignedInverse.card_goodCarriers_ge' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.SignedInverse.card_goodCarriers_ge

/-- info: 'Erdos289.SignedInverse.card_upperRank_ge' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.SignedInverse.card_upperRank_ge

/-- info: 'Erdos289.SignedInverse.GoodOrientation.atom_value_lt_of_le_coefficient' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.SignedInverse.GoodOrientation.atom_value_lt_of_le_coefficient

/-- info: 'Erdos289.SignedInverse.exists_injOn_subset' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.SignedInverse.exists_injOn_subset

/-- info: 'Erdos289.SignedInverse.card_upperCoefficient_ge' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.SignedInverse.card_upperCoefficient_ge

/-- info: 'Erdos289.SignedInverse.chosenCoefficientFiber_card_le_eight' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.SignedInverse.chosenCoefficientFiber_card_le_eight

/-- info: 'Erdos289.SignedInverse.exists_dedup_row' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.SignedInverse.exists_dedup_row

/-- info: 'Erdos289.SignedInverse.card_truncate_ge' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.SignedInverse.card_truncate_ge

/-- info: 'Erdos289.SignedInverse.exists_rowCertificate' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.SignedInverse.exists_rowCertificate

/-- info: 'Erdos289.mul_sub_le_mul_sub_of_between' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.mul_sub_le_mul_sub_of_between

/-- info: 'Erdos289.TransverseReservoir.restrictedFold_coversAtGrade_Icc' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.TransverseReservoir.restrictedFold_coversAtGrade_Icc

/-- info: 'Erdos289.exists_mem_lowerPrimePowerStage' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.exists_mem_lowerPrimePowerStage

/-- info: 'Erdos289.exists_saturationWitness_of_tailCovers' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.exists_saturationWitness_of_tailCovers

/-- info: 'Erdos289.cofiniteSaturation_one_of_core_tail' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.cofiniteSaturation_one_of_core_tail

/-- info: 'Erdos289.erdos289Statement_of_core_tail' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.erdos289Statement_of_core_tail

/-- info: 'Erdos289.Support.value_nonneg' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.Support.value_nonneg

/-- info: 'Erdos289.exists_lightPositive' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.exists_lightPositive

/-- info: 'Erdos289.exists_ladder' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.exists_ladder

/-- info: 'Erdos289.exists_lt_nsmul_of_mem_zmultiples' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.exists_lt_nsmul_of_mem_zmultiples

/-- info: 'Erdos289.exists_coreStage' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.exists_coreStage

/-- info: 'Erdos289.erdos289Statement_of_tailInterface' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.erdos289Statement_of_tailInterface

/-- info: 'AffineCorrection.intervalSpectrum_cofinite_of_eventually' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms AffineCorrection.intervalSpectrum_cofinite_of_eventually

/-- info: 'Erdos289.exists_tail_sum_lt' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.exists_tail_sum_lt

/-- info: 'Erdos289.exists_tail_sum_lt_rat' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.exists_tail_sum_lt_rat

/-- info: 'Erdos289.IndependentTransversal.exists_chunkPoolPartition' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.IndependentTransversal.exists_chunkPoolPartition

/-- info: 'Erdos289.exists_compatiblePool_of_binary_of_card' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.exists_compatiblePool_of_binary_of_card

/-- info: 'Erdos289.TransverseReservoir.mem_simpleValues_iff' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.TransverseReservoir.mem_simpleValues_iff

/-- info: 'Erdos289.aggregateSupport_stageClass' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.aggregateSupport_stageClass

/-- info: 'Erdos289.exists_pool_state_of_class' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.exists_pool_state_of_class

/-- info: 'Erdos289.tailStage_empty' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.tailStage_empty

/-- info: 'Erdos289.TailStage.comp' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.TailStage.comp

/-- info: 'Erdos289.tailStage_chain' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.tailStage_chain

/-- info: 'Erdos289.tailCovers_of_tailStage' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.tailCovers_of_tailStage

/-- info: 'Erdos289.TailStage.mono' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.TailStage.mono

/-- info: 'Erdos289.stageClass_eq_iff_sub_mem' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.stageClass_eq_iff_sub_mem

/-- info: 'Erdos289.tailStage_of_pool' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.tailStage_of_pool

/-- info: 'Erdos289.TailStage.mono_cost' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.TailStage.mono_cost

/-- info: 'Erdos289.tailCovers_of_stages' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.tailCovers_of_stages

/-- info: 'Erdos289.exists_lowerAnnihilator' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.exists_lowerAnnihilator

/-- info: 'Erdos289.reciprocalResidue_sub_notMem_lower' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.reciprocalResidue_sub_notMem_lower

/-- info: 'Erdos289.Support.stageClass_eq_iff' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.Support.stageClass_eq_iff

/-- info: 'Erdos289.TransverseReservoir.card_simpleValues_of_injective' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.TransverseReservoir.card_simpleValues_of_injective

/-- info: 'Erdos289.SignedInverse.atom_stageClass_ne_of_coefficient_ne' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Erdos289.SignedInverse.atom_stageClass_ne_of_coefficient_ne
