import Reciprocal.CenteredResidue

import Mathlib.Algebra.Group.Subgroup.Finite
import Mathlib.Data.ZMod.QuotientGroup
import Mathlib.GroupTheory.OrderOfElement
import Mathlib.Order.CompactlyGenerated.Basic

/-!
# Compact subgroup classification

The compact elements of the subgroup lattice of `A = ℚ/ℤ` are exactly the
finite cyclic subgroups `H_n = ker([n] : A → A)`.  Their cardinality is `n`,
their order relation is divisibility, and their finite joins and meets are
computed by `lcm` and `gcd`.
-/

namespace Erdos289

set_option linter.style.haveILetI false

/-- Multiplication by `n` on the centered residue group. -/
def residueMultiple (n : ℕ) : CenteredResidueGroup →+ CenteredResidueGroup :=
  AddMonoidHom.mk' (fun x ↦ n • x) fun a b ↦ smul_add n a b

/-- The compact subgroup `H_n = ker([n] : A → A)`. -/
def compactSubgroupH (n : ℕ) : AddSubgroup CenteredResidueGroup :=
  (residueMultiple n).ker

theorem mem_compactSubgroupH {n : ℕ} {x : CenteredResidueGroup} :
    x ∈ compactSubgroupH n ↔ n • x = 0 :=
  Iff.rfl

/-- The canonical generator of `H_n`, the class of `1/n`. -/
noncomputable def residueGen (n : ℕ) : CenteredResidueGroup :=
  centeredResidueQuotient (1 / (n : ℚ))

private theorem quotient_eq_zero_iff (q : ℚ) :
    centeredResidueQuotient q = 0 ↔ ∃ k : ℤ, q = (k : ℚ) := by
  rw [centeredResidueQuotient, QuotientAddGroup.mk'_apply, QuotientAddGroup.eq_zero_iff,
    AddSubgroup.mem_zmultiples_iff]
  constructor
  · rintro ⟨k, hk⟩
    exact ⟨k, by rw [← hk, zsmul_eq_mul, mul_one]⟩
  · rintro ⟨k, hk⟩
    exact ⟨k, by rw [hk, zsmul_eq_mul, mul_one]⟩

private theorem nsmul_quotient (n : ℕ) (q : ℚ) :
    n • centeredResidueQuotient q = centeredResidueQuotient ((n : ℚ) * q) := by
  rw [← map_nsmul, nsmul_eq_mul]

private theorem zsmul_quotient (k : ℤ) (q : ℚ) :
    k • centeredResidueQuotient q = centeredResidueQuotient ((k : ℚ) * q) := by
  rw [← map_zsmul, zsmul_eq_mul]

theorem mem_compactSubgroupH_quotient (n : ℕ) (q : ℚ) :
    centeredResidueQuotient q ∈ compactSubgroupH n ↔ ∃ k : ℤ, (n : ℚ) * q = (k : ℚ) := by
  rw [mem_compactSubgroupH, nsmul_quotient, quotient_eq_zero_iff]

theorem residueGen_mem {n : ℕ} (hn : 0 < n) : residueGen n ∈ compactSubgroupH n := by
  have hne : (n : ℚ) ≠ 0 := Nat.cast_ne_zero.2 hn.ne'
  rw [residueGen, mem_compactSubgroupH_quotient]
  exact ⟨1, by rw [mul_one_div, div_self hne, Int.cast_one]⟩

/-- R1.1: `H_n` consists exactly of the classes `j/n`, the cyclic subgroup
generated by the class of `1/n`. -/
theorem compactSubgroupH_eq_zmultiples {n : ℕ} (hn : 0 < n) :
    compactSubgroupH n = AddSubgroup.zmultiples (residueGen n) := by
  have hne : (n : ℚ) ≠ 0 := Nat.cast_ne_zero.2 hn.ne'
  apply le_antisymm
  · intro x hx
    obtain ⟨q, rfl⟩ :=
      QuotientAddGroup.mk'_surjective (AddSubgroup.zmultiples (1 : ℚ)) x
    obtain ⟨k, hk⟩ := (mem_compactSubgroupH_quotient n q).1 hx
    refine AddSubgroup.mem_zmultiples_iff.2 ⟨k, ?_⟩
    rw [residueGen, zsmul_quotient]
    congr 1
    rw [mul_one_div, div_eq_iff hne, ← hk]
    ring
  · rw [AddSubgroup.zmultiples_le]
    exact residueGen_mem hn

/-- R1.1: the class of `1/n` has additive order exactly `n`. -/
theorem addOrderOf_residueGen {n : ℕ} (hn : 0 < n) :
    addOrderOf (residueGen n) = n := by
  have hne : (n : ℚ) ≠ 0 := Nat.cast_ne_zero.2 hn.ne'
  have hzero : n • residueGen n = 0 := mem_compactSubgroupH.1 (residueGen_mem hn)
  refine Nat.dvd_antisymm (addOrderOf_dvd_of_nsmul_eq_zero hzero) ?_
  have hmem : residueGen n ∈ compactSubgroupH (addOrderOf (residueGen n)) :=
    mem_compactSubgroupH.2 (addOrderOf_nsmul_eq_zero (residueGen n))
  obtain ⟨k, hk⟩ :=
    (mem_compactSubgroupH_quotient (addOrderOf (residueGen n)) (1 / (n : ℚ))).1 hmem
  rw [mul_one_div, div_eq_iff hne] at hk
  have hz : ((addOrderOf (residueGen n) : ℤ)) = (n : ℤ) * k := by
    exact_mod_cast hk.trans (mul_comm _ _)
  exact_mod_cast Dvd.intro k hz.symm

/-- R1.1: `H_n` has cardinality `n`. -/
theorem card_compactSubgroupH {n : ℕ} (hn : 0 < n) :
    Nat.card (compactSubgroupH n) = n := by
  rw [compactSubgroupH_eq_zmultiples hn, Nat.card_zmultiples, addOrderOf_residueGen hn]

theorem finite_compactSubgroupH {n : ℕ} (hn : 0 < n) : Finite (compactSubgroupH n) :=
  Nat.finite_of_card_ne_zero (by rw [card_compactSubgroupH hn]; exact hn.ne')

/-- Uniqueness of the index: distinct positive indices give distinct compact
subgroups. -/
theorem compactSubgroupH_inj {n m : ℕ} (hn : 0 < n) (hm : 0 < m)
    (h : compactSubgroupH n = compactSubgroupH m) : n = m := by
  rw [← card_compactSubgroupH hn, ← card_compactSubgroupH hm, h]

/-- Divisibility gives inclusion of compact subgroups. -/
theorem compactSubgroupH_mono {n m : ℕ} (h : n ∣ m) :
    compactSubgroupH n ≤ compactSubgroupH m := by
  obtain ⟨c, rfl⟩ := h
  intro x hx
  rw [mem_compactSubgroupH] at hx ⊢
  rw [mul_comm, mul_smul, hx, smul_zero]

/-- R1.3: the order relation on compact subgroups is divisibility. -/
theorem compactSubgroupH_le_iff {n m : ℕ} (hn : 0 < n) :
    compactSubgroupH n ≤ compactSubgroupH m ↔ n ∣ m := by
  refine ⟨fun h ↦ ?_, compactSubgroupH_mono⟩
  have hzero : m • residueGen n = 0 := mem_compactSubgroupH.1 (h (residueGen_mem hn))
  have hdvd := addOrderOf_dvd_of_nsmul_eq_zero hzero
  rwa [addOrderOf_residueGen hn] at hdvd

/-- R1.3: meets of compact subgroups are computed by `gcd`. -/
theorem compactSubgroupH_inf (n m : ℕ) :
    compactSubgroupH n ⊓ compactSubgroupH m = compactSubgroupH (Nat.gcd n m) := by
  apply le_antisymm
  · intro x hx
    rw [AddSubgroup.mem_inf] at hx
    obtain ⟨hxn, hxm⟩ := hx
    rw [mem_compactSubgroupH] at hxn hxm ⊢
    exact addOrderOf_dvd_iff_nsmul_eq_zero.1
      (Nat.dvd_gcd (addOrderOf_dvd_of_nsmul_eq_zero hxn)
        (addOrderOf_dvd_of_nsmul_eq_zero hxm))
  · exact le_inf (compactSubgroupH_mono (Nat.gcd_dvd_left n m))
      (compactSubgroupH_mono (Nat.gcd_dvd_right n m))

/-- Every finite subgroup of `A` is the compact subgroup of its own
cardinality. -/
theorem eq_compactSubgroupH_of_finite (H : AddSubgroup CenteredResidueGroup)
    [Finite H] : H = compactSubgroupH (Nat.card H) := by
  have hpos : 0 < Nat.card H := Nat.card_pos
  have hle : H ≤ compactSubgroupH (Nat.card H) := by
    intro x hx
    rw [mem_compactSubgroupH]
    exact addOrderOf_dvd_iff_nsmul_eq_zero.1 (AddSubgroup.addOrderOf_dvd_natCard H hx)
  haveI : Finite (compactSubgroupH (Nat.card H)) := finite_compactSubgroupH hpos
  exact AddSubgroup.eq_of_le_of_card_ge hle (by rw [card_compactSubgroupH hpos])

/-- R1.3: joins of compact subgroups are computed by `lcm`. -/
theorem compactSubgroupH_sup {n m : ℕ} (hn : 0 < n) (hm : 0 < m) :
    compactSubgroupH n ⊔ compactSubgroupH m = compactSubgroupH (Nat.lcm n m) := by
  have hlcm : 0 < Nat.lcm n m := Nat.pos_of_ne_zero fun h ↦ by
    rcases Nat.eq_zero_of_lcm_eq_zero h with h' | h' <;> omega
  have hle : compactSubgroupH n ⊔ compactSubgroupH m ≤ compactSubgroupH (Nat.lcm n m) :=
    sup_le (compactSubgroupH_mono (Nat.dvd_lcm_left n m))
      (compactSubgroupH_mono (Nat.dvd_lcm_right n m))
  haveI : Finite (compactSubgroupH (Nat.lcm n m)) := finite_compactSubgroupH hlcm
  haveI : Finite (compactSubgroupH n ⊔ compactSubgroupH m : AddSubgroup _) :=
    ((Set.toFinite (↑(compactSubgroupH (Nat.lcm n m)) :
      Set CenteredResidueGroup)).subset (SetLike.coe_subset_coe.2 hle)).to_subtype
  have hd := eq_compactSubgroupH_of_finite (compactSubgroupH n ⊔ compactSubgroupH m)
  set d := Nat.card (compactSubgroupH n ⊔ compactSubgroupH m : AddSubgroup _) with hdef
  have hdpos : 0 < d := Nat.card_pos
  have hnd : n ∣ d := (compactSubgroupH_le_iff hn).1 (hd ▸ le_sup_left)
  have hmd : m ∣ d := (compactSubgroupH_le_iff hm).1 (hd ▸ le_sup_right)
  have hdl : d ∣ Nat.lcm n m := (compactSubgroupH_le_iff hdpos).1 (hd ▸ hle)
  rw [hd, Nat.dvd_antisymm hdl (Nat.lcm_dvd hnd hmd)]

private theorem directed_compactSubgroupPos :
    DirectedOn (· ≤ ·) (Set.range fun n : ℕ+ ↦ compactSubgroupH n) := by
  rintro _ ⟨n, rfl⟩ _ ⟨m, rfl⟩
  refine ⟨compactSubgroupH ((n * m : ℕ+) : ℕ), Set.mem_range.2 ⟨n * m, rfl⟩, ?_, ?_⟩
  · exact compactSubgroupH_mono ⟨(m : ℕ), by push_cast; ring⟩
  · exact compactSubgroupH_mono ⟨(n : ℕ), by push_cast; ring⟩

private theorem sSup_compactSubgroupPos :
    sSup (Set.range fun n : ℕ+ ↦ compactSubgroupH n) = ⊤ := by
  refine top_le_iff.1 fun x _ ↦ ?_
  obtain ⟨q, rfl⟩ := QuotientAddGroup.mk'_surjective (AddSubgroup.zmultiples (1 : ℚ)) x
  have hden : (0 : ℕ) < q.den := q.pos
  have hmem : centeredResidueQuotient q ∈ compactSubgroupH q.den := by
    rw [mem_compactSubgroupH_quotient]
    refine ⟨q.num, ?_⟩
    rw [mul_comm]
    exact_mod_cast Rat.mul_den_eq_num q
  have hsub : compactSubgroupH q.den ≤
      sSup (Set.range fun n : ℕ+ ↦ compactSubgroupH n) :=
    le_sSup (Set.mem_range.2 ⟨⟨q.den, hden⟩, rfl⟩)
  exact hsub hmem

/-- Every `H_n` with `n ≥ 1` is a compact element of the subgroup lattice. -/
theorem isCompactElement_compactSubgroupH {n : ℕ} (hn : 0 < n) :
    IsCompactElement (compactSubgroupH n) := by
  rw [CompleteLattice.isCompactElement_iff_le_of_directed_sSup_le]
  intro s hs hdir hle
  have hgen : residueGen n ∈ sSup s := hle (residueGen_mem hn)
  obtain ⟨K, hKs, hK⟩ := (AddSubgroup.mem_sSup_of_directedOn hs hdir).1 hgen
  refine ⟨K, hKs, ?_⟩
  rw [compactSubgroupH_eq_zmultiples hn, AddSubgroup.zmultiples_le]
  exact hK

/-- R1.2: the compact elements of the subgroup lattice of `A` are exactly the
subgroups `H_n` with `n ≥ 1`, and the index is unique. -/
theorem compactSubgroup_classification (H : AddSubgroup CenteredResidueGroup) :
    IsCompactElement H ↔ ∃! n : ℕ, 0 < n ∧ H = compactSubgroupH n := by
  constructor
  · intro hH
    obtain ⟨K, ⟨n, rfl⟩, hK⟩ :=
      hH _ ⊤ ⟨compactSubgroupH ((1 : ℕ+) : ℕ), Set.mem_range.2 ⟨1, rfl⟩⟩
        directed_compactSubgroupPos (sSup_compactSubgroupPos ▸ isLUB_sSup _) le_top
    haveI : Finite (compactSubgroupH ((n : ℕ+) : ℕ)) := finite_compactSubgroupH n.pos
    haveI : Finite H :=
      ((Set.toFinite (↑(compactSubgroupH ((n : ℕ+) : ℕ)) :
        Set CenteredResidueGroup)).subset (SetLike.coe_subset_coe.2 hK)).to_subtype
    refine ⟨Nat.card H, ⟨Nat.card_pos, eq_compactSubgroupH_of_finite H⟩, ?_⟩
    rintro d ⟨hd, hHd⟩
    exact compactSubgroupH_inj hd Nat.card_pos
      (hHd.symm.trans (eq_compactSubgroupH_of_finite H))
  · rintro ⟨n, ⟨hn, rfl⟩, -⟩
    exact isCompactElement_compactSubgroupH hn

@[simp]
theorem compactSubgroupH_one : compactSubgroupH 1 = ⊥ := by
  refine le_antisymm (fun x hx ↦ ?_) bot_le
  rw [mem_compactSubgroupH, one_smul] at hx
  exact AddSubgroup.mem_bot.2 hx

/-- The lattice `KSub(A)` of compact subgroups of the centered residue
group. -/
abbrev CompactSubgroupStage :=
  {H : AddSubgroup CenteredResidueGroup // IsCompactElement H}

namespace CompactSubgroupStage

/-- Every compact stage is `H_n` for `n` its own cardinality. -/
theorem eq_compactSubgroupH (J : CompactSubgroupStage) :
    J.1 = compactSubgroupH (Nat.card J.1) := by
  obtain ⟨n, ⟨hn, hJ⟩, -⟩ := (compactSubgroup_classification J.1).1 J.2
  rw [hJ, card_compactSubgroupH hn]

/-- The index of a compact stage: the cardinality of the underlying
subgroup. -/
noncomputable def index (J : CompactSubgroupStage) : ℕ := Nat.card J.1

theorem index_pos (J : CompactSubgroupStage) : 0 < J.index := by
  obtain ⟨n, ⟨hn, hJ⟩, -⟩ := (compactSubgroup_classification J.1).1 J.2
  rw [index, hJ, card_compactSubgroupH hn]
  exact hn

theorem coe_eq (J : CompactSubgroupStage) : J.1 = compactSubgroupH J.index :=
  eq_compactSubgroupH J

/-- The compact stage of a positive index. -/
def ofIndex (n : ℕ) (hn : 0 < n) : CompactSubgroupStage :=
  ⟨compactSubgroupH n, isCompactElement_compactSubgroupH hn⟩

@[simp]
theorem index_ofIndex (n : ℕ) (hn : 0 < n) : (ofIndex n hn).index = n :=
  card_compactSubgroupH hn

theorem ofIndex_index (J : CompactSubgroupStage) :
    ofIndex J.index J.index_pos = J :=
  Subtype.ext (coe_eq J).symm

theorem le_iff_index_dvd (J K : CompactSubgroupStage) :
    J ≤ K ↔ J.index ∣ K.index := by
  rw [show (J ≤ K) = (J.1 ≤ K.1) from rfl, coe_eq J, coe_eq K]
  exact compactSubgroupH_le_iff J.index_pos

theorem ext_index {J K : CompactSubgroupStage} (h : J.index = K.index) : J = K :=
  Subtype.ext (by rw [coe_eq J, coe_eq K, h])

private theorem sup_compact ⦃H K : AddSubgroup CenteredResidueGroup⦄
    (hH : IsCompactElement H) (hK : IsCompactElement K) :
    IsCompactElement (H ⊔ K) := by
  have hHe := eq_compactSubgroupH ⟨H, hH⟩
  have hKe := eq_compactSubgroupH ⟨K, hK⟩
  have hHp : 0 < Nat.card H := index_pos ⟨H, hH⟩
  have hKp : 0 < Nat.card K := index_pos ⟨K, hK⟩
  rw [show H = compactSubgroupH (Nat.card H) from hHe,
    show K = compactSubgroupH (Nat.card K) from hKe,
    compactSubgroupH_sup hHp hKp]
  exact isCompactElement_compactSubgroupH
    (Nat.pos_of_ne_zero fun h ↦ by
      rcases Nat.eq_zero_of_lcm_eq_zero h with h' | h' <;> omega)

private theorem inf_compact ⦃H K : AddSubgroup CenteredResidueGroup⦄
    (hH : IsCompactElement H) (hK : IsCompactElement K) :
    IsCompactElement (H ⊓ K) := by
  have hHe := eq_compactSubgroupH ⟨H, hH⟩
  have hKe := eq_compactSubgroupH ⟨K, hK⟩
  have hHp : 0 < Nat.card H := index_pos ⟨H, hH⟩
  have hKp : 0 < Nat.card K := index_pos ⟨K, hK⟩
  rw [show H = compactSubgroupH (Nat.card H) from hHe,
    show K = compactSubgroupH (Nat.card K) from hKe, compactSubgroupH_inf]
  exact isCompactElement_compactSubgroupH (Nat.gcd_pos_of_pos_left _ hHp)

noncomputable instance : Lattice CompactSubgroupStage :=
  Subtype.lattice sup_compact inf_compact

instance : OrderBot CompactSubgroupStage where
  bot := ⟨⊥, compactSubgroupH_one ▸ isCompactElement_compactSubgroupH Nat.one_pos⟩
  bot_le x := show (⊥ : AddSubgroup CenteredResidueGroup) ≤ x.1 from bot_le

@[simp]
theorem coe_bot : ((⊥ : CompactSubgroupStage) : AddSubgroup CenteredResidueGroup) = ⊥ :=
  rfl

@[simp]
theorem index_bot : (⊥ : CompactSubgroupStage).index = 1 := by
  rw [index, coe_bot]
  simp

theorem eq_bot_iff_index (J : CompactSubgroupStage) : J = ⊥ ↔ J.index = 1 := by
  refine ⟨fun h ↦ by rw [h, index_bot], fun h ↦ ext_index (by rw [h, index_bot])⟩

/-- R1.3: finite joins of compact stages are computed by `lcm`. -/
theorem index_sup (J K : CompactSubgroupStage) :
    (J ⊔ K).index = Nat.lcm J.index K.index := by
  have : ((J ⊔ K : CompactSubgroupStage) : AddSubgroup CenteredResidueGroup) =
      compactSubgroupH (Nat.lcm J.index K.index) := by
    show (J : AddSubgroup CenteredResidueGroup) ⊔ (K : AddSubgroup CenteredResidueGroup) = _
    rw [coe_eq J, coe_eq K, compactSubgroupH_sup J.index_pos K.index_pos]
  rw [index, this, card_compactSubgroupH]
  exact Nat.pos_of_ne_zero fun h ↦ by
    rcases Nat.eq_zero_of_lcm_eq_zero h with h' | h' <;>
      [exact absurd h' J.index_pos.ne'; exact absurd h' K.index_pos.ne']

/-- R1.3: finite meets of compact stages are computed by `gcd`. -/
theorem index_inf (J K : CompactSubgroupStage) :
    (J ⊓ K).index = Nat.gcd J.index K.index := by
  have : ((J ⊓ K : CompactSubgroupStage) : AddSubgroup CenteredResidueGroup) =
      compactSubgroupH (Nat.gcd J.index K.index) := by
    show (J : AddSubgroup CenteredResidueGroup) ⊓ (K : AddSubgroup CenteredResidueGroup) = _
    rw [coe_eq J, coe_eq K, compactSubgroupH_inf]
  rw [index, this, card_compactSubgroupH (Nat.gcd_pos_of_pos_left _ J.index_pos)]

end CompactSubgroupStage

end Erdos289
