module

/-
Copyright (c) 2026 Yuren Tang. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yuren Tang
-/

public import Mathlib.Combinatorics.SimpleGraph.Clique
public import Mathlib.Data.Finset.Card
public import Mathlib.Data.Setoid.Partition
import IndependentTransversals.Haxell

@[expose] public section

/-!
# Independent quota transversals

Packing is the nonemptiness of a canonical feasibility subobject: an
independent finite set meeting every prescribed pool quota.  Chunking and the
local lemma are proof technology and do not appear in this public object.
-/

set_option autoImplicit false
set_option relaxedAutoImplicit false

namespace Erdos289

universe u v

namespace IndependentTransversal

variable {V : Type u} {I : Type v} [DecidableEq V]

/-- The canonical block object generated by a family of finite pools. -/
def PoolBlocks (pools : I → Finset V) : Set (Set V) :=
  Set.range fun i => (pools i : Set V)

/-- The pools are exactly a partition of the vertex object. -/
def IsPoolPartition (pools : I → Finset V) : Prop :=
  Setoid.IsPartition (PoolBlocks pools)

/-- A global point of the independent one-per-chunk feasibility subobject. -/
def ChunkFeasible (G : SimpleGraph V) (pools : I → Finset V) :=
  {chosen : Set V //
    G.IsIndepSet chosen ∧
      ∀ i, ∃! v, v ∈ chosen ∩ (pools i : Set V)}

/--
A chunk transversal is at least as large as the number of chunks: it meets each
chunk exactly once, and distinct chunks are disjoint.  Preserving this count is
what makes the packing theorem quantitative.
-/
theorem card_le_card_chosen {V I : Type*} [DecidableEq V] [Fintype I]
    {G : SimpleGraph V} {pools : I → Finset V}
    (hdisj : ∀ i j : I, i ≠ j → Disjoint (pools i) (pools j))
    (f : ChunkFeasible G pools) [Fintype f.1] :
    Fintype.card I ≤ f.1.toFinset.card := by
  classical
  have hex : ∀ i : I, ∃ v, v ∈ f.1 ∩ (pools i : Set V) := fun i => (f.2.2 i).exists
  have hcard : Fintype.card I = (Finset.univ : Finset I).card := (Finset.card_univ).symm
  rw [hcard]
  refine Finset.card_le_card_of_injOn (fun i => (hex i).choose) ?_ ?_
  · intro i _
    exact Set.mem_toFinset.2 (hex i).choose_spec.1
  · intro i _ j _ hij
    by_contra hne
    have hi : (hex i).choose ∈ pools i := (hex i).choose_spec.2
    have hj : (hex j).choose ∈ pools j := (hex j).choose_spec.2
    have hij' : (hex i).choose = (hex j).choose := hij
    rw [hij'] at hi
    exact (Finset.disjoint_left.1 (hdisj i j hne)) hi hj

/-- The pools admit a chunk-feasible independent global section. -/
def HasChunkPacking (G : SimpleGraph V) (pools : I → Finset V) : Prop :=
  Nonempty (ChunkFeasible G pools)

/-- A finite selection meets all row quotas. -/
def MeetsQuotas
    (pools : I → Finset V) (quota : I → ℕ) (chosen : Finset V) : Prop :=
  ∀ i, quota i ≤ (chosen ∩ pools i).card

/-- The independent-transversal feasibility object. -/
def Feasible
    (G : SimpleGraph V) (pools : I → Finset V) (quota : I → ℕ) :=
  {chosen : Finset V //
    G.IsIndepSet (chosen : Set V) ∧ MeetsQuotas pools quota chosen}

/-- The exact global-section assertion: an independent set meeting every quota. -/
def HasPacking
    (G : SimpleGraph V) (pools : I → Finset V) (quota : I → ℕ) : Prop :=
  Nonempty (Feasible G pools quota)

section Haxell

variable [Fintype V]

/--
Haxell's independent-transversal theorem: a partition into chunks of size at
least twice the maximum conflict degree has an independent global section.
-/
theorem hasChunkPacking_of_two_mul_maxDegree_le
    (G : SimpleGraph V) [DecidableRel G.Adj] (pools : I → Finset V)
    (hpartition : IsPoolPartition pools)
    (hthick : ∀ i, 2 * G.maxDegree ≤ (pools i).card) :
    HasChunkPacking G pools := by
  let PG : _root_.IndependentTransversals.PartitionedGraph V :=
    { graph := G
      blocks := PoolBlocks pools
      isPartition := hpartition }
  have hPGthick : PG.isThick (2 * PG.graph.maxDegree) := by
    intro U hU
    rcases hU with ⟨i, rfl⟩
    simpa [PG] using hthick i
  obtain ⟨S, hS⟩ := PG.haxell_theorem hPGthick
  exact ⟨⟨S, hS.1, fun i => hS.2 _ ⟨i, rfl⟩⟩⟩

/-- The one-per-chunk theorem supplies the quota interface with constant quota one. -/
theorem hasPacking_one_of_two_mul_maxDegree_le
    (G : SimpleGraph V) [DecidableRel G.Adj] (pools : I → Finset V)
    (hpartition : IsPoolPartition pools)
    (hthick : ∀ i, 2 * G.maxDegree ≤ (pools i).card) :
    HasPacking G pools (fun _ => 1) := by
  rcases hasChunkPacking_of_two_mul_maxDegree_le G pools hpartition hthick with
    ⟨⟨S, hSindep, hSblocks⟩⟩
  let _ : Fintype S := Fintype.ofFinite S
  refine ⟨⟨S.toFinset, ?_, ?_⟩⟩
  · simpa using hSindep
  · intro i
    rcases hSblocks i with ⟨v, hv, _⟩
    apply Finset.one_le_card.mpr
    exact ⟨v, by simpa using hv⟩

end Haxell

end IndependentTransversal

end Erdos289
