module

/-
Copyright (c) 2026 Yuren Tang. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yuren Tang
-/

public import Mathlib.Algebra.BigOperators.Group.Finset.Basic
public import Mathlib.Combinatorics.SimpleGraph.Connectivity.Finite
public import Mathlib.Data.Nat.Dist
public import Mathlib.Data.PNat.Basic
public import Mathlib.Data.Rat.Defs

@[expose] public section

/-!
# Finite reciprocal supports on the positive-integer path

Blocks are connected components of the graph induced by a finite support in
the path on positive integers.  Thus a block is not represented by a chosen
interval decomposition: it is an element of the quotient by the equivalence
relation generated by adjacency.
-/

set_option autoImplicit false
set_option relaxedAutoImplicit false

open scoped BigOperators

namespace Erdos289

/-- Positive denominators. -/
abbrev Denominator := ℕ+

/-- A finite set of distinct positive denominators. -/
abbrev Support := Finset Denominator

/-- The path graph on positive integers. -/
def denominatorPath : SimpleGraph Denominator where
  Adj a b := a.1 + 1 = b.1 ∨ b.1 + 1 = a.1
  symm := ⟨fun _ _ h => h.elim Or.inr Or.inl⟩
  loopless := ⟨fun a h => by omega⟩

@[simp]
theorem denominatorPath_adj (a b : Denominator) :
    denominatorPath.Adj a b ↔ a.1 + 1 = b.1 ∨ b.1 + 1 = a.1 :=
  Iff.rfl

instance : DecidableRel denominatorPath.Adj := fun a b =>
  inferInstanceAs (Decidable (a.1 + 1 = b.1 ∨ b.1 + 1 = a.1))

/-- The graph induced by a finite reciprocal support. -/
def Support.graph (S : Support) : SimpleGraph {n : Denominator // n ∈ S} :=
  denominatorPath.induce (S : Set Denominator)

/--
The component quotient of a support.  This is the Set-level coequalizer of the
two endpoint maps of the induced adjacency graph.
-/
abbrev Support.Blocks (S : Support) := S.graph.ConnectedComponent

/-- Number of connected components (blocks) of a support. -/
noncomputable def Support.grade (S : Support) : ℕ :=
  Nat.card S.Blocks

/-- Cardinality of one connected component. -/
noncomputable def Support.blockSize {S : Support} (c : S.Blocks) : ℕ :=
  Nat.card c.supp

/-- Reciprocal weight of one positive denominator. -/
def reciprocal (n : Denominator) : ℚ :=
  1 / (n.1 : ℚ)

/-- Exact reciprocal value, the finite additive extension of `n ↦ 1/n`. -/
def Support.value (S : Support) : ℚ :=
  ∑ n ∈ S, reciprocal n

@[simp]
theorem Support.value_empty : (∅ : Support).value = 0 := by
  simp [Support.value]

/-- Exact value is additive on disjoint union. -/
theorem Support.value_union
    {S T : Support} (h : Disjoint S T) :
    (S ∪ T).value = S.value + T.value := by
  simp [Support.value, Finset.sum_union h]

/-- A finite obstacle and a required inter-block separation margin. -/
structure PhysicalConstraint where
  /-- Denominators forbidden to the support. -/
  obstacle : Support
  /-- Required strict lower bound on distances between distinct blocks. -/
  separation : ℕ

/-- One support avoids the finite obstacle. -/
def Support.Avoids (S : Support) (c : PhysicalConstraint) : Prop :=
  Disjoint S c.obstacle

/-- Distinct blocks of a support are separated by more than the given margin. -/
def Support.Separated (S : Support) (margin : ℕ) : Prop :=
  ∀ (c d : S.Blocks), c ≠ d →
    ∀ (x : {n : Denominator // n ∈ S}), x ∈ c.supp →
    ∀ (y : {n : Denominator // n ∈ S}), y ∈ d.supp →
      margin < Nat.dist x.1.1 y.1.1

/-- Every block size lies in the prescribed intrinsic set of allowed sizes. -/
def Support.HasBlockSizes (S : Support) (L : Set ℕ) : Prop :=
  ∀ c : S.Blocks, S.blockSize c ∈ L

/-- The constrained finite-support subobject used by the E289 specialization. -/
def Support.Admissible
    (L : Set ℕ) (c : PhysicalConstraint) (S : Support) : Prop :=
  S.HasBlockSizes L ∧ S.Avoids c ∧ S.Separated c.separation

/-- The component sizes used by the construction: two and three. -/
def smallBlockSizes : Set ℕ := {n | n = 2 ∨ n = 3}

/-- The component-size condition in the original Erdős problem. -/
def nontrivialBlockSizes : Set ℕ := {n | 2 ≤ n}

theorem smallBlockSizes_subset_nontrivial :
    smallBlockSizes ⊆ nontrivialBlockSizes := by
  intro n hn
  change n = 2 ∨ n = 3 at hn
  change 2 ≤ n
  rcases hn with rfl | rfl <;> omega

end Erdos289
