module

/-
Copyright (c) 2026 Yuren Tang. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yuren Tang
-/

public import Erdos289.PrimePowerFiltration
public import Erdos289.Statement
import Mathlib.Tactic.Linarith

@[expose] public section

/-!
# The unit selector

Centering by the target replaces the exact value group `ℚ` by `ℚ/ℤ`.  A state
whose centered residue vanishes has integer value, so on the open interval
`(0, 2)` — the two adjacent lifts of the target residue surrounding the target —
the centered condition already pins the value to `1`.

This is the reciprocal specialization of the selector used by the universal
exact-fibre transfer theorem: `(0, 2) ∩ ℤ = {1}`.  Nothing here chooses a
witness; it converts a residue condition into an exact value.
-/

set_option autoImplicit false
set_option relaxedAutoImplicit false

namespace Erdos289

/--
The selector interval of a positive target `r` is `(0, 2 r)`, and it meets the
subgroup generated by `r` in the single point `r`: the two adjacent integer
multiples of `r` surrounding it are `0` and `2 r`.
-/
theorem eq_of_mem_zmultiples_of_lt_two_mul {r q : ℚ} (hr : 0 < r)
    (hmem : q ∈ AddSubgroup.zmultiples r) (h0 : 0 < q) (h2 : q < 2 * r) :
    q = r := by
  rw [AddSubgroup.mem_zmultiples_iff] at hmem
  obtain ⟨n, hn⟩ := hmem
  have hq : q = (n : ℚ) * r := by
    rw [← hn, zsmul_eq_mul]
  subst hq
  have h0' : (0 : ℤ) < n := by
    by_contra hcon
    have : (n : ℚ) ≤ 0 := by exact_mod_cast Int.not_lt.1 hcon
    nlinarith
  have h2' : n < (2 : ℤ) := by
    by_contra hcon
    have : (2 : ℚ) ≤ (n : ℚ) := by exact_mod_cast Int.not_lt.1 hcon
    nlinarith
  have hn1 : n = 1 := by omega
  rw [hn1]
  norm_num

/-- The specialization to the unit target. -/
theorem eq_one_of_mem_zmultiples_of_lt_two {q : ℚ}
    (hmem : q ∈ AddSubgroup.zmultiples (1 : ℚ)) (h0 : 0 < q) (h2 : q < 2) :
    q = 1 :=
  eq_of_mem_zmultiples_of_lt_two_mul (by norm_num) hmem h0 (by simpa using h2)

/--
The selector step at an arbitrary positive target: a support whose value lies
in `(0, 2 r)` and whose `r`-centred residue vanishes has value exactly `r`.
-/
theorem Support.value_eq_of_centredResidue_zero {r : ℚ} (hr : 0 < r) {S : Support}
    (h0 : 0 < S.value) (h2 : S.value < 2 * r)
    (hres : AffineCorrection.CenteredValue.mk r S.value = 0) : S.value = r := by
  refine eq_of_mem_zmultiples_of_lt_two_mul hr ?_ h0 h2
  exact (QuotientAddGroup.eq_zero_iff S.value).1 hres

/--
The unit-target specialization, which is the one Erdős 289 uses.
-/
theorem Support.value_eq_one_of_residue_zero {S : Support}
    (h0 : 0 < S.value) (h2 : S.value < 2) (hres : S.residue = 0) :
    S.value = 1 := by
  refine eq_one_of_mem_zmultiples_of_lt_two ?_ h0 h2
  exact (QuotientAddGroup.eq_zero_iff S.value).1 hres

/--
An admissible support of grade `k` that is centered and lies in the selector
interval is a saturation witness at the unit target.
-/
def saturationWitness_of_residue_zero
    {L : Set ℕ} {c : PhysicalConstraint} {k : ℕ} {S : Support}
    (hadm : S.Admissible L c) (hgrade : S.grade = k)
    (h0 : 0 < S.value) (h2 : S.value < 2) (hres : S.residue = 0) :
    SaturationWitness L 1 c k where
  support := S
  admissible := hadm
  value_eq := Support.value_eq_one_of_residue_zero h0 h2 hres
  grade_eq := hgrade

/--
Cofinite saturation at the unit target follows from a family of centered
admissible supports realizing every sufficiently large grade inside the
selector interval.
-/
theorem cofiniteSaturation_one_of_centered
    {L : Set ℕ} {c : PhysicalConstraint} {N : ℕ}
    (h : ∀ k, N ≤ k → ∃ S : Support, S.Admissible L c ∧
      S.grade = k ∧ 0 < S.value ∧ S.value < 2 ∧ S.residue = 0) :
    CofiniteSaturation L 1 c := by
  refine ⟨N, fun k hk => ?_⟩
  obtain ⟨S, hadm, hgrade, h0, h2, hres⟩ := h k hk
  exact ⟨saturationWitness_of_residue_zero hadm hgrade h0 h2 hres⟩

end Erdos289
