#!/usr/bin/env python3
"""Regenerate `Audit.lean` with pinned `#print axioms` output.

`Audit.lean` is generated rather than hand-written so that the expected axiom
set of every exported theorem is *observed* and then frozen with `#guard_msgs`.
Freezing matters: without it a `sorryAx` arriving through a dependency would
merely change a line of build output instead of failing the build.

Usage (from the package root, after `lake build`):

    python3 scripts/gen_audit.py

The declarations to audit are listed one per line in `scripts/audit_decls.txt`.
A declaration whose observed axiom set is not the accepted foundational triple
is reported and the script refuses to write the file.
"""

from __future__ import annotations

import pathlib
import re
import subprocess
import sys
import tempfile

ROOT = pathlib.Path(__file__).resolve().parent.parent
DECLS = ROOT / "scripts" / "audit_decls.txt"
TARGET = ROOT / "Audit.lean"

# The ordinary foundations inherited from mathlib.  A declaration may depend on
# any subset of these; anything else — a project axiom, or `sorryAx` — is a
# trust failure.
ACCEPTED = {"propext", "Classical.choice", "Quot.sound"}

PREAMBLE = """module

/-
Copyright (c) 2026 Yuren Tang. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yuren Tang
-/

public import Erdos289
import Erdos289.SignedInverse
import Erdos289.SignedInverseAtom
import Erdos289.SignedInverseReservoir
import Erdos289.SignedInverseConflict
import Erdos289.RowSupply
import Erdos289.BadCarriers

/-!
# Transitive trust audit

`lake build` succeeding means every declaration has a proof term.  It does not
mean the proof closure is free of assumptions: a theorem can be fully elaborated
and still depend transitively on a `sorry` upstream.  This module is the check
that does mean that.

Each exported theorem's transitive axiom set is pinned with `#guard_msgs`, so a
`sorryAx` or a new project axiom introduced by any future change — including one
arriving through a dependency bump — turns the build red instead of scrolling
past in a log.  The accepted dependencies are the ordinary foundations inherited
from mathlib.

This file is generated by `scripts/gen_audit.py`; edit `scripts/audit_decls.txt`
and regenerate rather than editing it by hand.
-/

"""


def read_decls() -> list[str]:
    names = []
    for line in DECLS.read_text().splitlines():
        line = line.strip()
        if line and not line.startswith("--"):
            names.append(line)
    return names


def probe(names: list[str]) -> dict[str, str]:
    """Elaborate a throwaway module of plain `#print axioms` and read it back."""
    body = PREAMBLE + "\n".join(f"#print axioms {n}" for n in names) + "\n"
    with tempfile.NamedTemporaryFile(
        "w", suffix=".lean", dir=ROOT, delete=False
    ) as fh:
        fh.write(body)
        probe_path = pathlib.Path(fh.name)
    try:
        result = subprocess.run(
            ["lake", "env", "lean", str(probe_path)],
            cwd=ROOT,
            capture_output=True,
            text=True,
        )
    finally:
        probe_path.unlink(missing_ok=True)

    if result.returncode != 0 and not result.stdout:
        sys.exit(f"probe failed:\n{result.stderr}")

    observed: dict[str, str] = {}
    pattern = re.compile(r"'([^']+)' depends on axioms: (\[[^\]]*\])", re.S)
    for name, axioms in pattern.findall(result.stdout):
        observed[name] = " ".join(axioms.split())
    for name in names:
        if name in result.stdout and name not in observed:
            observed[name] = "[]"
    return observed


def main() -> None:
    names = read_decls()
    observed = probe(names)

    missing = [n for n in names if n not in observed]
    if missing:
        sys.exit("no axiom report for: " + ", ".join(missing))

    def offending(axioms: str) -> list[str]:
        inner = axioms.strip()[1:-1].strip()
        listed = [a.strip() for a in inner.split(",") if a.strip()]
        return [a for a in listed if a not in ACCEPTED]

    bad = {n: offending(a) for n, a in observed.items() if offending(a)}
    if bad:
        for name, axioms in bad.items():
            print(f"unexpected axioms for {name}: {axioms}", file=sys.stderr)
        sys.exit(
            "refusing to regenerate: only "
            f"{sorted(ACCEPTED)} are accepted; a project axiom or sorryAx is present"
        )

    chunks = [
        f"/-- info: '{name}' depends on axioms: {observed[name]} -/\n"
        f"#guard_msgs (whitespace := lax) in\n"
        f"#print axioms {name}\n"
        for name in names
    ]
    TARGET.write_text(PREAMBLE + "\n".join(chunks))
    print(f"wrote {TARGET.relative_to(ROOT)} with {len(names)} pinned audits")


if __name__ == "__main__":
    main()
