#!/usr/bin/env python3
"""Regenerate `Audit.lean` with pinned `#print axioms` output.

`Audit.lean` is generated rather than hand-written so that the expected axiom
set of every public declaration is *observed* and then frozen with
`#guard_msgs`.  Freezing matters: without it a `sorryAx` arriving through a
dependency would merely change a line of build output instead of failing the
build.

The audited set is *derived from the sources* by `scripts/public_decls.py` —
every declaration of `Erdos289/` and `AffineCorrection/` not marked `private` —
so coverage is complete by construction and a new public theorem cannot escape
the audit by being forgotten in a list.

Usage (from the package root, after `lake build`):

    python3 scripts/gen_audit.py

A declaration whose observed axiom set is not the accepted foundational triple
is reported and the script refuses to write the file.
"""

from __future__ import annotations

import pathlib
import re
import subprocess
import sys
import tempfile

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
TARGET = ROOT / "Audit.lean"

# The ordinary foundations inherited from mathlib.  A declaration may depend on
# any subset of these; anything else — a project axiom, or `sorryAx` — is a
# trust failure.
ACCEPTED = {"propext", "Classical.choice", "Quot.sound"}

def all_modules() -> list[str]:
    """Every module of the package, so that the audit can name every
    declaration — including the ones the publication root does not re-export."""
    mods = []
    for directory in ("Erdos289", "AffineCorrection"):
        base = ROOT / directory
        for path in sorted(base.rglob("*.lean")):
            rel = path.relative_to(ROOT).with_suffix("")
            mods.append(".".join(rel.parts))
    return mods


PREAMBLE = """module

/-
Copyright (c) 2026 Yuren Tang. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yuren Tang
-/

public import Erdos289
""" + "".join(f"import {m}\n" for m in all_modules()) + """

/-!
# Transitive trust audit

`lake build` succeeding means every declaration has a proof term.  It does not
mean the proof closure is free of assumptions: a theorem can be fully elaborated
and still depend transitively on a `sorry` upstream.  This module is the check
that does mean that.

Each exported theorem's transitive axiom set is pinned with `#guard_msgs`, so a
`sorryAx` or a new project axiom introduced by any future change — including one
arriving through a dependency bump — turns the build red instead of scrolling
past in a log.  The accepted dependencies are the ordinary foundations inherited
from mathlib.

The audited set is every public declaration of `Erdos289/` and
`AffineCorrection/`, derived from the sources rather than maintained by hand,
so its coverage of the package is complete by construction.

This file is generated by `scripts/gen_audit.py`; regenerate rather than
editing it by hand.
-/

"""


def read_decls() -> list[str]:
    from public_decls import public_declarations

    return public_declarations()


def probe(names: list[str]) -> dict[str, str]:
    """Elaborate a throwaway module of plain `#print axioms` and read it back."""
    body = PREAMBLE + "\n".join(f"#print axioms {n}" for n in names) + "\n"
    with tempfile.NamedTemporaryFile(
        "w", suffix=".lean", dir=ROOT, delete=False
    ) as fh:
        fh.write(body)
        probe_path = pathlib.Path(fh.name)
    try:
        result = subprocess.run(
            ["lake", "env", "lean", str(probe_path)],
            cwd=ROOT,
            capture_output=True,
            text=True,
        )
    finally:
        probe_path.unlink(missing_ok=True)

    if result.returncode != 0 and not result.stdout:
        sys.exit(f"probe failed:\n{result.stderr}")

    observed: dict[str, str] = {}
    pattern = re.compile(r"'([^']+)' depends on axioms: (\[[^\]]*\])", re.S)
    for name, axioms in pattern.findall(result.stdout):
        observed[name] = "depends on axioms: " + " ".join(axioms.split())
    axiomless = re.compile(r"'([^']+)' does not depend on any axioms")
    for name in axiomless.findall(result.stdout):
        observed.setdefault(name, "does not depend on any axioms")
    return observed


def main() -> None:
    names = read_decls()
    observed = probe(names)

    missing = [n for n in names if n not in observed]
    if missing:
        sys.exit("no axiom report for: " + ", ".join(missing))

    def offending(message: str) -> list[str]:
        if not message.startswith("depends on axioms: "):
            return []
        inner = message[len("depends on axioms: "):].strip()[1:-1].strip()
        listed = [a.strip() for a in inner.split(",") if a.strip()]
        return [a for a in listed if a not in ACCEPTED]

    bad = {n: offending(a) for n, a in observed.items() if offending(a)}
    if bad:
        for name, axioms in bad.items():
            print(f"unexpected axioms for {name}: {axioms}", file=sys.stderr)
        sys.exit(
            "refusing to regenerate: only "
            f"{sorted(ACCEPTED)} are accepted; a project axiom or sorryAx is present"
        )

    chunks = [
        f"/-- info: '{name}' {observed[name]} -/\n"
        f"#guard_msgs (whitespace := lax) in\n"
        f"#print axioms {name}\n"
        for name in names
    ]
    TARGET.write_text(PREAMBLE + "\n".join(chunks))
    print(f"wrote {TARGET.relative_to(ROOT)} with {len(names)} pinned audits")


if __name__ == "__main__":
    main()
