module

/-
Copyright (c) 2026 Yuren Tang. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yuren Tang
-/

public import Mathlib.Algebra.Group.Subgroup.ZPowers.Basic
public import Mathlib.GroupTheory.QuotientGroup.Defs

@[expose] public section

/-!
# Canonical target centering

For a marked additive group `(Γ, τ)`, the centered value group is the cokernel
of the mark `ℤ →+ Γ`, `1 ↦ τ`.  In additive-group language this cokernel is the
quotient by the cyclic subgroup generated by `τ`.

The quotient presentation below is the Lean realization of that reflection;
its universal property is exported explicitly.  No merely sufficient subgroup
annihilating `τ` is chosen.
-/

set_option autoImplicit false
set_option relaxedAutoImplicit false

namespace AffineCorrection

universe u v

/-- The centered exact-value group `coker(ℤ → Γ, 1 ↦ τ)`. -/
abbrev CenteredValue (Γ : Type u) [AddCommGroup Γ] (τ : Γ) :=
  Γ ⧸ AddSubgroup.zmultiples τ

namespace CenteredValue

variable {Γ : Type u} [AddCommGroup Γ] (τ : Γ)

/-- The canonical quotient map from exact values to centered values. -/
def mk : Γ →+ CenteredValue Γ τ :=
  QuotientAddGroup.mk' (AddSubgroup.zmultiples τ)

@[simp]
theorem mk_apply (x : Γ) : mk τ x = (x : CenteredValue Γ τ) :=
  rfl

/-- Centering annihilates the marked target. -/
@[simp]
theorem mk_target : mk τ τ = 0 := by
  apply (QuotientAddGroup.eq_zero_iff τ).2
  rw [AddSubgroup.mem_zmultiples_iff]
  exact ⟨1, one_zsmul τ⟩

/--
The factor through the centered quotient induced by a homomorphism annihilating
the target.
-/
def desc
    {A : Type v} [AddCommGroup A]
    (f : Γ →+ A) (hτ : f τ = 0) : CenteredValue Γ τ →+ A :=
  QuotientAddGroup.lift (AddSubgroup.zmultiples τ) f <|
    AddSubgroup.zmultiples_le.mpr (AddMonoidHom.mem_ker.mpr hτ)

@[simp]
theorem desc_mk
    {A : Type v} [AddCommGroup A]
    (f : Γ →+ A) (hτ : f τ = 0) (x : Γ) :
    desc τ f hτ (mk τ x) = f x :=
  by
    change
      QuotientAddGroup.lift (AddSubgroup.zmultiples τ) f
        (AddSubgroup.zmultiples_le.mpr (AddMonoidHom.mem_ker.mpr hτ))
        (x : CenteredValue Γ τ) = f x
    exact QuotientAddGroup.lift_mk' _ _ x

/-- The descended map composes with the quotient map to the original map. -/
theorem desc_comp_mk
    {A : Type v} [AddCommGroup A]
    (f : Γ →+ A) (hτ : f τ = 0) :
    (desc τ f hτ).comp (mk τ) = f :=
  QuotientAddGroup.lift_comp_mk' _ _ _

/-- Uniqueness in the cokernel universal property. -/
theorem desc_unique
    {A : Type v} [AddCommGroup A]
    (f : Γ →+ A) (hτ : f τ = 0)
    (g : CenteredValue Γ τ →+ A)
    (hg : g.comp (mk τ) = f) :
    g = desc τ f hτ := by
  apply QuotientAddGroup.addMonoidHom_ext (AddSubgroup.zmultiples τ)
  calc
    g.comp (QuotientAddGroup.mk' (AddSubgroup.zmultiples τ)) = f := by
      simpa [mk] using hg
    _ = (desc τ f hτ).comp
        (QuotientAddGroup.mk' (AddSubgroup.zmultiples τ)) := by
      simpa [mk] using (desc_comp_mk τ f hτ).symm

/--
Existence and uniqueness of factorization through target centering, stated as
the reflection property consumed by later observation systems.
-/
theorem lift_unique
    {A : Type v} [AddCommGroup A]
    (f : Γ →+ A) (hτ : f τ = 0) :
    ∃! g : CenteredValue Γ τ →+ A, g.comp (mk τ) = f := by
  refine ⟨desc τ f hτ, desc_comp_mk τ f hτ, ?_⟩
  intro g hg
  exact desc_unique τ f hτ g hg

end CenteredValue

end AffineCorrection
