module

/-
Copyright (c) 2026 Yuren Tang. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yuren Tang
-/

public import Mathlib.Algebra.Group.Action.Defs
public import Mathlib.Algebra.Field.ZMod
public import Mathlib.Data.Fin.Basic
public import Mathlib.Data.Set.Image

@[expose] public section

/-!
# The monogenic cyclic ladder

The ladder is the orbit map of the free monogenic action.  Its public
hypothesis is surjectivity of that canonical orbit map; no coordinate or
chosen decoding algorithm is retained.
-/

set_option autoImplicit false
set_option relaxedAutoImplicit false

namespace AffineCorrection

universe u

namespace CyclicLadder

variable {A : Type u} [AddGroup A]

/-- The finite prefix of the orbit generated by `c`. -/
def orbit (c : A) (N : ℕ) : Fin (N + 1) → A :=
  fun n => n.1 • c

/-- The first `N+1` points of the monogenic orbit cover the carrier. -/
def GeneratesIn (c : A) (N : ℕ) : Prop :=
  Function.Surjective (orbit c N)

/-- Translating a covering monogenic orbit gives a covering affine orbit. -/
theorem affine_orbit_surjective
    {c : A} {N : ℕ} (h : GeneratesIn c N) (γ : A) :
    Function.Surjective (fun n : Fin (N + 1) => γ + orbit c N n) := by
  intro x
  rcases h (-γ + x) with ⟨n, hn⟩
  refine ⟨n, ?_⟩
  change γ + orbit c N n = x
  rw [hn]
  simp

/-- Set-level image formulation of affine orbit coverage. -/
theorem range_affine_orbit
    {c : A} {N : ℕ} (h : GeneratesIn c N) (γ : A) :
    Set.range (fun n : Fin (N + 1) => γ + orbit c N n) = Set.univ := by
  exact Set.range_eq_univ.mpr (affine_orbit_surjective h γ)

/-- Every nonzero point of the one-dimensional prime field generates its additive carrier. -/
theorem zmod_generatesIn_pred
    {p : ℕ} (hp : p.Prime) (c : ZMod p) (hc : c ≠ 0) :
    GeneratesIn c (p - 1) := by
  let _ : Fact p.Prime := ⟨hp⟩
  unfold GeneratesIn orbit
  rw [Nat.sub_add_cancel hp.one_le]
  intro x
  let q : ZMod p := x / c
  let n : Fin p := ⟨q.val, q.val_lt⟩
  refine ⟨n, ?_⟩
  change n.1 • c = x
  rw [nsmul_eq_mul]
  change (q.val : ZMod p) * c = x
  rw [ZMod.natCast_zmod_val]
  exact div_mul_cancel₀ x hc

end CyclicLadder

end AffineCorrection
