module

/-
Copyright (c) 2026 Yuren Tang. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yuren Tang
-/

public import AffineCorrection.CompactResolution

@[expose] public section

/-!
# The least compact absorber

For a compact stage `H` and a label `d : A ⧸ H`, the absorber is the pullback
of the cyclic image generated by `d` along the quotient map `A → A ⧸ H`.
It is the least compact extension of `H` at which `d` becomes zero.
-/

set_option autoImplicit false
set_option relaxedAutoImplicit false

namespace AffineCorrection

universe u

namespace LeastAbsorber

variable {A : Type u} [AddCommGroup A]

/-- The cyclic-image pullback defining the intrinsic absorber subgroup. -/
def subgroup (H : CompactStage A) (d : A ⧸ H.1) : AddSubgroup A :=
  (AddSubgroup.zmultiples d).comap (QuotientAddGroup.mk' H.1)

/-- A representative used only to prove finite generation of the absorber. -/
noncomputable def representative (H : CompactStage A) (d : A ⧸ H.1) : A :=
  Classical.choose (QuotientAddGroup.mk'_surjective H.1 d)

@[simp]
theorem representative_spec (H : CompactStage A) (d : A ⧸ H.1) :
    QuotientAddGroup.mk' H.1 (representative H d) = d :=
  Classical.choose_spec (QuotientAddGroup.mk'_surjective H.1 d)

/-- The absorber contains the stage from which its label was observed. -/
theorem stage_le_subgroup (H : CompactStage A) (d : A ⧸ H.1) :
    H.1 ≤ subgroup H d := by
  intro x hx
  change QuotientAddGroup.mk' H.1 x ∈ AddSubgroup.zmultiples d
  have hzero : QuotientAddGroup.mk' H.1 x = 0 :=
    (QuotientAddGroup.eq_zero_iff x).2 hx
  rw [hzero]
  exact (AddSubgroup.zmultiples d).zero_mem

/--
The pullback definition equals the join of the old stage with the cyclic
subgroup generated by any chosen lift.  The equality is a proof theorem, not
the definition of the absorber.
-/
theorem subgroup_eq_sup (H : CompactStage A) (d : A ⧸ H.1) :
    subgroup H d = H.1 ⊔ AddSubgroup.zmultiples (representative H d) := by
  let q : A →+ (A ⧸ H.1) := QuotientAddGroup.mk' H.1
  calc
    subgroup H d =
        (AddSubgroup.map q (AddSubgroup.zmultiples (representative H d))).comap q := by
      rw [AddMonoidHom.map_zmultiples, representative_spec]
      rfl
    _ = AddSubgroup.zmultiples (representative H d) ⊔ q.ker :=
      AddSubgroup.comap_map_eq q _
    _ = AddSubgroup.zmultiples (representative H d) ⊔ H.1 := by
      rw [QuotientAddGroup.ker_mk']
    _ = H.1 ⊔ AddSubgroup.zmultiples (representative H d) := sup_comm _ _

theorem zmultiples_fg (a : A) : (AddSubgroup.zmultiples a).FG := by
  refine ⟨{a}, ?_⟩
  rw [AddSubgroup.zmultiples_eq_closure]
  congr 1
  ext x
  simp

/-- The intrinsic absorber is compact. -/
theorem subgroup_fg (H : CompactStage A) (d : A ⧸ H.1) :
    (subgroup H d).FG := by
  rw [subgroup_eq_sup]
  exact H.2.sup (zmultiples_fg (representative H d))

/-- The least absorber as an object of the compact-stage poset. -/
noncomputable def stage (H : CompactStage A) (d : A ⧸ H.1) : CompactStage A :=
  ⟨subgroup H d, subgroup_fg H d⟩

@[simp]
theorem stage_coe (H : CompactStage A) (d : A ⧸ H.1) :
    (stage H d).1 = subgroup H d :=
  rfl

theorem le_stage (H : CompactStage A) (d : A ⧸ H.1) : H ≤ stage H d :=
  stage_le_subgroup H d

/-- The canonical transition to an extension kills `d` exactly above the absorber. -/
theorem transition_eq_zero_iff
    (H K : CompactStage A) (hHK : H ≤ K) (d : A ⧸ H.1) :
    CompactResolution.transition A hHK d = 0 ↔ stage H d ≤ K := by
  let a := representative H d
  have ha : QuotientAddGroup.mk' H.1 a = d := representative_spec H d
  change CompactResolution.transition A hHK d = 0 ↔ subgroup H d ≤ K.1
  rw [subgroup_eq_sup]
  constructor
  · intro hd
    apply sup_le hHK
    rw [AddSubgroup.zmultiples_le]
    apply (QuotientAddGroup.eq_zero_iff a).1
    calc
      QuotientAddGroup.mk' K.1 a =
          CompactResolution.transition A hHK
            (QuotientAddGroup.mk' H.1 a) := by
        symm
        exact CompactResolution.transition_mk A hHK a
      _ = CompactResolution.transition A hHK d := by rw [ha]
      _ = 0 := hd
  · intro hle
    have haK : a ∈ K.1 :=
      (AddSubgroup.zmultiples_le.mp (le_sup_right.trans hle))
    rw [← ha]
    rw [CompactResolution.transition_mk]
    exact (QuotientAddGroup.eq_zero_iff a).2 haK

/-- Minimality formulation of the absorber universal property. -/
theorem minimal
    (H K : CompactStage A) (hHK : H ≤ K) (d : A ⧸ H.1)
    (hkill : CompactResolution.transition A hHK d = 0) :
    stage H d ≤ K :=
  (transition_eq_zero_iff H K hHK d).1 hkill

end LeastAbsorber

end AffineCorrection
