name: Lean

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: leanprover/lean-action@v1
        with:
          auto-config: false
          build: false
          test: false
          lint: false
      - name: Resolve dependencies
        run: lake update
      - name: Restore Mathlib cache
        run: lake exe cache get
      - name: Build
        run: lake build
